# Generated by Django 2.2.28 on 2023-03-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thepetproject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('date_joined', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, upload_to=thepetproject.models.UserProfile.get_correct_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=500)),
                ('date_posted', models.DateField()),
                ('time_posted', models.TimeField()),
                ('likes', models.IntegerField(default=0)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=thepetproject.models.Post.get_correct_directory)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thepetproject.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('date_posted', models.DateField()),
                ('time_posted', models.TimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thepetproject.Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
