# Generated by Django 2.2.28 on 2023-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thepetproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
