# Generated by Django 2.2.28 on 2023-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thepetproject', '0005_auto_20230307_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
